project:
  type: website
  output-dir: docs

website:
  title: "Sobhan Khosravi Zadeh"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



